#!/usr/bin/env python3
"""Generate the twelve canonical solution pages."""
from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://budzetplus.rs"
LASTMOD = "2026-08-26"

# slug, title, description, kicker, h1, intro, benefits, process, related slugs
PAGES = [
    ("program-za-racunovodstvo-skola", "Automatizovano knjigovodstvo za škole | Budžet+", "Budžet+ pretvara eFakture, SPIRI izvode i obračune u naloge bez mehaničkog prepisivanja, uz proveru i potvrdu računovođe.", "Automatizovano knjigovodstvo", "Automatizovano knjigovodstvo za škole", "Budžet+ uklanja mehaničko prepisivanje iz školskog knjigovodstva. eFakture, SPIRI izvodi i obračuni postaju pripremljeni nalozi, dok računovođa proverava i potvrđuje.", ["Budžetski kontni plan, izvori, projekti i programske aktivnosti", "eFakture, SPIRI izvodi i ISKRA obračuni u istom toku", "Glavna knjiga, dnevnik, kartice, bilansi i pomoćne evidencije", "SPIRI, ORIS i ISPFI fajlovi iz proverenih podataka"], ["Dokument ili obračun se učita.", "Budžet+ prepoznaje podatke i priprema poslovne promene.", "Računovođa proverava konta, klasifikacije i iznose.", "Potvrđen nalog ulazi u knjige, preglede i izveštaje."], ["knjizenje-e-faktura-za-skole", "spiri-izvodi-skole", "iskra-obracuni-knjizenje"]),
    ("knjizenje-e-faktura-za-skole", "eFakture za automatsko knjiženje | Budžet+", "Preuzimanje e-faktura iz SEF-a, rad sa partnerima i pojedinačno ili masovno knjiženje uz završnu proveru računovođe.", "SEF i e-fakture", "eFakture za automatsko knjiženje", "Budžet+ preuzima dostupne podatke iz SEF-a, povezuje ili kreira partnere i priprema pojedinačne ili masovne naloge bez ponovnog kucanja.", ["Preuzimanje podataka sa e-faktura iz SEF-a", "Prepoznavanje i kreiranje partnera", "Pojedinačna obrada kada je potrebna posebna kontrola", "Masovno knjiženje odabranih faktura"], ["Preuzmite e-fakture iz SEF-a.", "Proverite partnera, stavke i klasifikaciju.", "Izaberite pojedinačno ili masovno knjiženje.", "Pregledajte i potvrdite pripremljene naloge."], ["program-za-racunovodstvo-skola", "spiri-kumulativno-placanje", "oris-izvoz-za-skole"]),
    ("spiri-izvodi-skole", "SPIRI izvodi za automatsko knjiženje | Budžet+", "Učitajte SPIRI izvod i pretvorite njegove stavke u poslovne promene spremne za računovodstvenu proveru i knjiženje.", "SPIRI izvodi", "SPIRI izvodi za automatsko knjiženje", "Učitani SPIRI izvod postaje skup pripremljenih poslovnih promena. Računovođa proverava predloge pre knjiženja.", ["Učitavanje SPIRI izvoda", "Prepoznavanje stavki i poslovnih promena", "Povezivanje sa partnerima i evidencijom", "Kontrolisan nalog bez ručnog prepisivanja"], ["Učitajte SPIRI izvod.", "Budžet+ priprema poslovne promene.", "Proverite stavke, konta i klasifikacije.", "Potvrdite nalog i koristite podatke u pregledima."], ["program-za-racunovodstvo-skola", "izvrsenje-budzeta-skola", "knjizenje-e-faktura-za-skole"]),
    ("iskra-obracuni-knjizenje", "ISKRA obračuni za automatsko knjiženje | Budžet+", "Plate, bolovanja, RFZO i prevoz iz ISKRA obračuna pripremljeni za knjiženje bez ručnog unosa svake stavke.", "Plate, bolovanja, RFZO i prevoz", "ISKRA obračuni za automatsko knjiženje", "Budžet+ učitava podatke iz ISKRA obračuna i priprema nalog koji računovođa pregleda i potvrđuje.", ["Obračuni plata", "Bolovanja i RFZO podaci", "Obračuni prevoza", "Pregled naloga pre potvrde"], ["Izaberite ISKRA obračun.", "Program učitava i raspoređuje podatke.", "Pregledajte pripremljene stavke i kontrole.", "Potvrdite nalog za knjiženje."], ["program-za-racunovodstvo-skola", "spiri-izvodi-skole", "zatvaranje-poslovne-godine"]),
    ("spiri-kumulativno-placanje", "SPIRI plaćanje iz e-faktura | Budžet+", "Objedinite više e-faktura u jedan dokument za SPIRI kumulativno plaćanje, uz pregled računovođe pre učitavanja.", "Kumulativno plaćanje", "SPIRI plaćanje iz e-faktura", "Izaberite više e-faktura i pripremite jedan dokument za kumulativno plaćanje u SPIRI, bez ponovnog unosa podataka.", ["Podaci se preuzimaju sa e-faktura", "Više obaveza u jednom dokumentu", "Manji rizik greške pri prepisivanju", "Pregled pre učitavanja u SPIRI"], ["Izaberite e-fakture za plaćanje.", "Budžet+ objedinjuje dostupne podatke.", "Pregledajte iznose, partnere i pozive na broj.", "Učitajte pripremljeni dokument u SPIRI."], ["knjizenje-e-faktura-za-skole", "rucni-unos-spiri-placanja", "spiri-izvodi-skole"]),
    ("rucni-unos-spiri-placanja", "Ručni SPIRI unos sa šablonima | Budžet+", "Pripremite SPIRI plaćanja za partnere i fizička lica, učitajte poresku prijavu i sačuvajte šablone za ponovljena plaćanja.", "Plaćanja koja ne polaze od e-fakture", "Ručni SPIRI sa šablonima", "Kada plaćanje ne polazi od e-fakture, Budžet+ vodi kroz izbor primaoca i podataka, a ponovljena plaćanja ubrzava sačuvanim šablonima.", ["Izbor partnera ili fizičkog lica", "Učitavanje podataka iz poreske prijave", "Lista sačuvanih šablona", "Dokument spreman za proveru i SPIRI"], ["Izaberite partnera, fizičko lice ili poresku prijavu.", "Unesite ili proverite podatke plaćanja.", "Sačuvajte raspored kao šablon za sledeći put.", "Pregledajte i pripremite dokument za SPIRI."], ["spiri-kumulativno-placanje", "spiri-izvodi-skole", "program-za-racunovodstvo-skola"]),
    ("oris-izvoz-za-skole", "ORIS izvoz za škole | Budžet+", "Pripremite kontrolisan fajl za ORIS iz postojećih knjiženja, bez vođenja posebne paralelne evidencije.", "ORIS izvoz", "Kontrolisan ORIS fajl bez paralelne evidencije", "Budžet+ priprema ORIS fajl iz podataka koji se već vode i proveravaju u računovodstvu škole.", ["Podaci dolaze iz postojeće evidencije", "Kontrole pre pripreme fajla", "Manje naknadnog usklađivanja", "Fajl spreman za učitavanje na ORIS portal"], ["Ažurirajte redovna knjiženja.", "Pokrenite ORIS kontrole.", "Ispravite ili potvrdite označene stavke.", "Preuzmite pripremljeni fajl za ORIS."], ["program-za-racunovodstvo-skola", "obrazac-5-ispfi", "izvrsenje-budzeta-skola"]),
    ("obrazac-5-ispfi", "Obrazac 5 za ISPFI | Budžet+", "Pripremite obavezni Obrazac 5 za ISPFI iz postojećih proknjiženih podataka bez ponovnog ručnog unosa.", "Iz postojećih podataka", "Obrazac 5 spreman za ISPFI", "Budžet+ koristi postojeća knjiženja za pripremu Obrasca 5, a računovođa proverava rezultat pre učitavanja u ISPFI.", ["Bez ponovnog unosa istih podataka", "Priprema iz završenih knjiženja", "Kraći rad pred rok", "Fajl spreman za ISPFI"], ["Proverite da su knjiženja završena.", "Pokrenite pripremu Obrasca 5.", "Pregledajte i preuzmite rezultat.", "Učitajte fajl u ISPFI i izvršite završnu proveru."], ["oris-izvoz-za-skole", "izvrsenje-budzeta-skola", "program-za-racunovodstvo-skola"]),
    ("izvrsenje-budzeta-skola", "Izvršenje budžeta za škole | Budžet+", "Pratite plan, realizaciju, odstupanja i grafikone, uz poređenje računovodstvenih podataka sa SPIRI.", "Plan i realizacija", "Izvršenje budžeta pod kontrolom", "Plan, realizacija i odstupanja vide se iz podataka koji se već vode, uz grafikone i poređenje sa SPIRI.", ["Plan i realizacija budžeta", "Odstupanja koja se brzo uočavaju", "Grafikoni i pregledi", "Poređenje evidencije sa SPIRI"], ["Unesite ili uvezite plan.", "Knjiženja ažuriraju realizaciju.", "Pregledajte odstupanja i grafikone.", "Uporedite podatke sa SPIRI i proverite razlike."], ["spiri-izvodi-skole", "oris-izvoz-za-skole", "obrazac-5-ispfi"]),
    ("osnovna-sredstva-skola", "Osnovna sredstva i amortizacija za škole | Budžet+", "Vodite osnovna sredstva, uvezite postojeće podatke, obračunajte amortizaciju i pripremite popisne liste.", "Evidencija i popis", "Osnovna sredstva škole", "Budžet+ objedinjuje evidenciju osnovnih sredstava, uvoz, amortizaciju i popisne liste.", ["Evidencija osnovnih sredstava", "Uvoz postojećih podataka", "Obračun amortizacije", "Popisne liste i pregledi"], ["Unesite ili uvezite sredstva.", "Proverite podatke i klasifikaciju.", "Obračunajte amortizaciju.", "Pripremite popisne liste i preglede."], ["zatvaranje-poslovne-godine", "program-za-racunovodstvo-skola", "izvrsenje-budzeta-skola"]),
    ("uplate-ucenika", "Uplate učenika po aktivnosti | Budžet+", "Pratite učenike, aktivnosti, zaduženja i uplate uz jasne preglede po učeniku, odeljenju i aktivnosti.", "Školska pomoćna evidencija", "Uplate učenika pregledne po aktivnosti", "Budžet+ povezuje učenike, aktivnosti, zaduženja i uplate, pa su pregledi dostupni bez dodatnih tabela.", ["Učenici i odeljenja", "Aktivnosti i zaduženja", "Evidentiranje i uvoz uplata", "Pregledi po učeniku i aktivnosti"], ["Definišite učenike i aktivnosti.", "Kreirajte zaduženja.", "Evidentirajte ili uvezite uplate.", "Koristite zbirne i pojedinačne preglede."], ["program-za-racunovodstvo-skola", "izvrsenje-budzeta-skola", "osnovna-sredstva-skola"]),
    ("zatvaranje-poslovne-godine", "Zatvaranje godine i prenos salda | Budžet+", "Završite poslovnu godinu kroz obračun amortizacije, zatvaranje konta, prenos salda i otvaranje nove godine.", "Kontrolisan završni tok", "Zatvaranje godine i prenos salda", "Budžet+ vodi računovođu kroz jasan redosled završnih koraka, uz proveru pre prenosa stanja u novu poslovnu godinu.", ["Obračun amortizacije", "Zatvaranje konta", "Prenos salda i početnih stanja", "Otvaranje nove poslovne godine"], ["Obračunajte i proverite amortizaciju.", "Pregledajte i zatvorite odgovarajuća konta.", "Prenesite salda i početna stanja.", "Otvorite novu poslovnu godinu i proverite prenete podatke."], ["osnovna-sredstva-skola", "program-za-racunovodstvo-skola", "izvrsenje-budzeta-skola"]),
]

LABELS = {p[0]: p[4] for p in PAGES}
def esc(value: str) -> str:
    return html.escape(value, quote=True)


def render(page: tuple) -> str:
    slug, title, desc, kicker, h1, intro, benefits, process, related = page
    canonical = f"{BASE}/{slug}/"
    schema = {"@context": "https://schema.org", "@graph": [
        {"@type": "WebPage", "@id": canonical, "url": canonical, "name": title, "description": desc, "isPartOf": {"@id": f"{BASE}/#website"}, "about": {"@id": f"{BASE}/#software"}, "inLanguage": "sr", "dateModified": LASTMOD},
        {"@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Početna", "item": f"{BASE}/"}, {"@type": "ListItem", "position": 2, "name": h1, "item": canonical}]},
    ]}
    items = "".join(f"<li>{esc(x)}</li>" for x in benefits)
    steps = "".join(f"<li>{esc(x)}</li>" for x in process)
    links = "".join(f'<a href="../{s}/">{esc(LABELS[s])} &rarr;</a>' for s in related)
    schema_json = json.dumps(schema, ensure_ascii=False, separators=(",", ":"))
    return f'''<!doctype html><html lang="sr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/assets/img/budzet-plus-social.svg"><script type="application/ld+json">{schema_json}</script><link rel="stylesheet" href="../assets/styles.css"></head><body class="landing-body"><header class="landing-header"><div class="container landing-nav"><a class="landing-brand" href="../">Budžet+ za škole</a><a class="btn primary" href="../#kontakt">Zakažite prezentaciju</a></div></header><main><nav class="container breadcrumbs" aria-label="Putanja"><ol><li><a href="../">Početna</a></li><li>/</li><li>{esc(h1)}</li></ol></nav><section class="landing-hero"><div class="container landing-hero-grid"><div><p class="landing-kicker">{esc(kicker)}</p><h1>{esc(h1)}</h1><p class="lede">{esc(intro)}</p></div><aside class="landing-summary"><h2>Šta dobijate</h2><ul>{items}</ul></aside></div></section><section class="section alt"><div class="container content-narrow"><h2>Manje mehaničkog rada, puna stručna kontrola</h2><p>Program priprema podatke i sledeći korak. Računovođa proverava rezultat i potvrđuje stručne odluke.</p><h2>Kako izgleda rad</h2><ol class="process-list">{steps}</ol><div class="landing-cta"><h2>Pogledajte Budžet+ u radu</h2><a class="btn primary" href="../#kontakt">Zakažite prezentaciju</a></div><h2>Povezana rešenja</h2><div class="related-links">{links}</div></div></section></main><footer class="landing-footer"><div class="container landing-footer-inner"><p><strong>Budžet+ za škole</strong><br>Automatizovano knjigovodstvo uz kontrolu računovođe</p><p><a href="mailto:aleksandar.pejkovic@budzetplus.rs">aleksandar.pejkovic@budzetplus.rs</a></p></div></footer></body></html>\n'''


def main() -> None:
    for page in PAGES:
        target = ROOT / page[0] / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(page), encoding="utf-8")
    urls = [f"{BASE}/"] + [f"{BASE}/{p[0]}/" for p in PAGES]
    body = "\n".join(f"  <url><loc>{u}</loc><lastmod>{LASTMOD}</lastmod></url>" for u in urls)
    (ROOT / "sitemap.xml").write_text(f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{body}\n</urlset>\n', encoding="utf-8")


if __name__ == "__main__":
    main()
